import os
from dotenv import load_dotenv

load_dotenv()
SECRET_KEY = os.getenv('SECRET_KEY')

ACCESS_EXPIRE_TOKEN=int(os.getenv('ACCESS_EXPIRE_TOKEN'))
REFRESH_EXPIRE_TOKEN=int(os.getenv('REFRESH_EXPIRE_TOKEN'))
ALGORITHM=os.getenv('ALGORITHM')

GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID')
GOOGLE_CLIENT_SECRET = os.getenv('GOOGLE_CLIENT_SECRET')
GOOGLE_REDIRECT_URI = os.getenv('GOOGLE_REDIRECT_URI')
FRONTEND_URL = os.getenv('FRONTEND_URL')