"""empty message

Revision ID: 14b0a3678811
Revises: dbebdd6cff62
Create Date: 2026-09-17 17:40:50.716213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14b0a3678811'
down_revision: Union[str, Sequence[str], None] = 'dbebdd6cff62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_player', sa.Column('has_sent_last_words', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_player', 'has_sent_last_words')
    # ### end Alembic commands ###
