"""empty message

Revision ID: c128b19cc8cf
Revises: b7ed56ecbdc7
Create Date: 2026-10-08 14:02:44.078498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c128b19cc8cf'
down_revision: Union[str, Sequence[str], None] = 'b7ed56ecbdc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_statistics', sa.Column('coins', sa.Integer(), nullable=False))
    op.add_column('user_statistics', sa.Column('protections', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_statistics', 'protections')
    op.drop_column('user_statistics', 'coins')
    # ### end Alembic commands ###
