"""empty message

<<<<<<<< HEAD:migrations/versions/14b0a3678811_.py
Revision ID: 14b0a3678811
Revises: dbebdd6cff62
Create Date: 2026-09-17 17:40:50.716213
========
Revision ID: fa3b44ca5315
Revises: 6a8242be7bfe
Create Date: 2026-09-17 16:41:21.208861
>>>>>>>> origin/bakir:migrations/versions/fa3b44ca5315_.py

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/14b0a3678811_.py
revision: str = '14b0a3678811'
down_revision: Union[str, Sequence[str], None] = 'dbebdd6cff62'
========
revision: str = 'fa3b44ca5315'
down_revision: Union[str, Sequence[str], None] = '6a8242be7bfe'
>>>>>>>> origin/bakir:migrations/versions/fa3b44ca5315_.py
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
<<<<<<<< HEAD:migrations/versions/14b0a3678811_.py
    op.add_column('game_player', sa.Column('has_sent_last_words', sa.Boolean(), nullable=False))
========
    op.add_column('room', sa.Column('age', sa.SmallInteger(), nullable=False))
>>>>>>>> origin/bakir:migrations/versions/fa3b44ca5315_.py
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
<<<<<<<< HEAD:migrations/versions/14b0a3678811_.py
    op.drop_column('game_player', 'has_sent_last_words')
========
    op.drop_column('room', 'age')
>>>>>>>> origin/bakir:migrations/versions/fa3b44ca5315_.py
    # ### end Alembic commands ###
