"""empty message

Revision ID: fa3b44ca5315
Revises: 6a8242be7bfe
Create Date: 2026-09-17 16:41:21.208861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa3b44ca5315'
down_revision: Union[str, Sequence[str], None] = '6a8242be7bfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('age', sa.SmallInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'age')
    # ### end Alembic commands ###
